language: node_js
node_js:
  - '18'
dist: bionic
addons:
  apt:
    update: true
script: yarn run build
deploy:
  provider: npm
  edge: true
  email: nat@natwelch.com
  api_token: $NPM_API_TOKEN
  cleanup: false
  on:
    tags: true
    repo: icco/react-common
