language: node_js
node_js:
- stable
script: yarn run build
deploy:
  provider: npm
  email: nat@natwelch.com
  api_key:
    secure: PkKSVCKUr58dk7XEyf6/9r7RM79G2t60PwRpgOc4lZGWdleyntWSdlvqWSygUtrJIfgrxawKQz16Xs2H66I9l87CJM0y0H2aKpvWmLe9xT7AglKQTIXv+vvR8x/jT5XvI7aTjJQsoBrjju79CeDWCGoPCUl6YLoQTf8o22h/nAXGPbw/Dfqi1TzGn0wzK4pgqDUMWV+2I78qmEwM/G/IbTNMoVOuOEs9Ag2xll3VlUnfwQWu0CFcbnmjbXN8LV6LTk807H7czzTCmxSyy1qj8aJejIlE3/LYlr2N04cW424LkUKMer5ZYwW5X37sxaEuK1CGP3tfJO5WTEAUSP9wp+NmB3KFljqVcqh2POSa7lkTIfRHdmmOrPba9HcZHAW7NdwP6YsO2hGDji1siRZTQMy0Wg3ZmBSpVhnTvDKNzEiFFEeuD9wQdagRr4rlWygbDFAQ9udO6SqEFcyXPhgc5lJOFY+kVBzjE5cxwl29G6xiHx5wc3//V9sUI3oJVdI3ioRRpEbWreHJEMVsjmms8RT2jWaEojeczy18gDoaZUG+Cw4DSoHUjQqZWzru5QwJ/0PnQrVHtnhTlVJ4WN2DEP8nF+YW7+MzaprQUxmv9bhcnVzlXmKWcIoLkNwR/VXR7Z6eDH8Tnffp6d2q3dxieyl8xxKiWwjDTlovvRfR7Xo=
  on:
    tags: true
    repo: icco/react-common
  skip_cleanup: 'true'
