name: Publish Package to npmjs
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org
      - run: yarn
      - run: yarn build
      - name: Version and publish
        run: |
          DATE=$(date +%Y.%-m.%-d)
          OLDVERSION=$(jq -r ".version" package.json)
          OLDDATE=$(echo $OLDVERSION | sed 's/-.*$//')
          OLDINT=$(echo $OLDVERSION | sed 's/^.*-//')

          INT=1
          if [ "${DATE}" = "${OLDDATE}" ]; then
            INT=$(($OLDINT + 1))
          fi

          VERSION=${DATE}-${INT}
          jq ".version = \"$VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json

          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
